### ISSUE TITLE
Does not load in Blender 5.1

### ISSUE THREAD

**Issue by Arahnoid** [Trukasss/ResetWorkspace#2]
Thank you for this great addon I use it a lot, however it does not load in the newest version of Blender. Below is the log from Blender system console.

```
Exception in module register(): C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\blender_org\reset_workspace\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 5.1\5.1\scripts\modules\addon_utils.py", line 515, in enable
    mod.register()
    ~~~~~~~~~~~~^^
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\blender_org\reset_workspace\__init__.py", line 51, in register
    icons.register()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\blender_org\reset_workspace\icons.py", line 12, in register
    _icons.load(
    ~~~~~~~~~~~^
        name="reset",
        ^^^^^^^^^^^^^
        path=str(icons_dir / "icon_reset.png"),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        path_type="IMAGE")
        ^^^^^^^^^^^^^^^^^^
TypeError: ImagePreviewCollection.load() got an unexpected keyword argument 'path'
```

It still works in 5.0 but not in 5.1

**Comment by rutgerrrrr** [comment]
I've fixed the issue here [https://github.com/Trukasss/ResetWorkspace/pull/3](https://github.com/Trukasss/ResetWorkspace/pull/3)

**Comment by Arahnoid** [comment]
I tried to download it again from Blender Extensions site  the version is 0.0.4

````
ImagePreviewCollection.load() got an unexpected keyword argument 'path'

**Comment by rutgerrrrr** [comment]
> I tried to download it again from Blender Extensions site  the version is 0.0.4
> 
> ````
> ImagePreviewCollection.load() got an unexpected keyword argument 'path'
> 

The fix hasn't been implemented yet by the repo owner. You can use my version though.

**Comment by Arahnoid** [comment]
@rutgerrrrr oh now I see. I thought you were the repo owner 😄

**Comment by AlphaCraft9658** [comment]
Any updates? It would be great if the fix could be merged into this repository.

**Comment by rutgerrrrr** [comment]
> Any updates? It would be great if the fix could be merged into this repository.

I've implemented the fix in a pull request but unless the repo owner merges it the issue will remain. You can use my fork though.
